name: "PR Validations"

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  
permissions:
  pull-requests: read

jobs:
  main:
    name: Semantic Pull Request Validation
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            setup
          requireScope: false

